question_data = {"response_code": 0, 
                 "results": [{"category": "Sports", 
                              "type": "multiple", 
                              "difficulty": "medium", 
                              "question": "In a game of snooker, what colour ball is worth 3 points?", 
                              "correct_answer": "Green", 
                              "incorrect_answers": ["Yellow", "Brown", "Blue"]}, 
                             
                             {"category": "Science: Computers", "type": "multiple", "difficulty": "easy", "question": "Which computer hardware device provides an interface for all other connected devices to communicate?", "correct_answer": "Motherboard", "incorrect_answers": ["Central Processing Unit", "Hard Disk Drive", "Random Access Memory"]}, {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy", "question": "Who is the main protagonist in, the 1985 film, Back to the Future?", "correct_answer": "Marty McFly", "incorrect_answers": ["Emmett &quot;Doc&quot; Brown", "Biff Tannen", "George McFly"]}, {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium", "question": "What is the last song on the first Panic! At the Disco album?", "correct_answer": "Build God, Then We&#039;ll Talk", "incorrect_answers": ["Nails for Breakfast, Tacks for Snacks", "I Write Sins Not Tragedies", "Lying Is The Most Fun A Girl Can Have Without Taking Her Clothes Off"]}, {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "question": "How many members are in the Japanese rock band SCANDAL?", "correct_answer": "4", "incorrect_answers": ["5", "2", "18"]}, {"category": "History", "type": "boolean", "difficulty": "hard", "question": "The USS Missouri (BB-63) last served in the Korean War.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "General Knowledge", "type": "multiple", "difficulty": "medium", "question": "The website &quot;Shut Up &amp; Sit Down&quot; reviews which form of media?", "correct_answer": "Board Games", "incorrect_answers": ["Television Shows", "Video Games", "Films"]}, {"category": "History", "type": "multiple", "difficulty": "easy", "question": "Which country was Josef Stalin born in?", "correct_answer": "Georgia", "incorrect_answers": ["Russia", "Germany", "Poland"]}, {"category": "General Knowledge", "type": "multiple", "difficulty": "medium", "question": "What is the highest number of Michelin stars a restaurant can receive?", "correct_answer": "Three", "incorrect_answers": ["Four", "Five", "Six"]}, {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy", "question": "Which Nintendo 64 game did NOT have Luigi in it?", "correct_answer": "Super Mario 64", "incorrect_answers": ["Mario Party 2", "Paper Mario", "Super Smash Bros."]}]}
